### ISSUE TITLE
Does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [CREDITSCOM/cscrypto#1]
```
/run/firejail/appimage/.appimage-8902/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-8902/AppRun)
/run/firejail/appimage/.appimage-8902/AppRun: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /run/firejail/appimage/.appimage-8902/usr/bin/../lib/libpng16.so.16)
```

Please build on the oldest still-supported LTS release.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1645

**Comment by SychevS** [comment]
Thanks for your remark @probonopd. Rebuilt on Ubuntu 14.04 LTS. AppImage file updated in release:
https://github.com/CREDITSCOM/cscrypto/releases/tag/v0.2.0_gui

Issue closed, feel free to reopen.
